### PR TITLE
OS X Compatibility + clang support + fixes for compiler warnings

### PR DESCRIPTION
**Pull request by MichaelEischer**
The first commit fixes compilation using clang.
Compile support for Mac OS X is added (not sure that everything works).
Last the signedness warnings are fixed.

### CODE REVIEW

**Comment by Hawk777** [comment]
Hi Michael, I merged three of your four commits (53c1f5c needed a small fix after it, which I have also committed). I noticed in bb6f253 that you edited both configuration.cc (to add casts to unsigned int) and also configuration.h (to change the variables to int). I believe you only meant to change configuration.cc, and that the variables in configuration.h should remain unsigned int. Could you please rebase and amend bb6f253 appropriately? Thanks!

**Comment by MichaelEischer** [comment]
I've changed configuration.h on purpose as these variables are used as stage time which is signed. Changing configuration.h was the fastest fix for the signedness warnings. I can implement the requested changes, but I'd rather prefer my current solution.

**Comment by Hawk777** [comment]
I’m not 100% happy with the concept of total stage time being signed; the length of a game stage can, after all, never be negative (that would be physically impossible). It could be zero, but not negative. However, I guess it’s not such a bad solution given how the data is used, so yes, I’ll take it. I wasn’t able to actually reproduce the compiler warnings these patches fix (neither GCC 4.8.4 nor Clang 3.5.0 give any warnings without the patches), but they do make sense.

**Comment by MichaelEischer** [comment]
g++ 4.9.1 on Ubuntu 14.10 doesn't show these warnings either.
For me clang++ 3.5 on Ubuntu and clang-3.6 (more or less) on OS X generate warnings without the last patch.

**Pull request merged**
